version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: kopikami_mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: kopikami_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -uuser -ppassword"]
      interval: 10s
      retries: 5
      start_period: 20s

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kopikami_app
    ports:
      - "8080:8080"
    environment:
      DB_USER: user
      DB_PASS: password
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: kopikami_db
    depends_on:
      mysql:
        condition: service_healthy
    restart: always

volumes:
  mysql_data:
